services:
  - type: web
    name: lista-cafe
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: flutter run -d web-server --web-hostname 0.0.0.0 --web-port $PORT
    envVars:
      - key: PORT
        value: 8080
      - key: FLUTTER_VERSION
        value: '3.19.0'
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - lib/**
        - pubspec.yaml
        - pubspec.lock
        - web/**
        - android/**
        - ios/**
        - linux/**
        - macos/**
        - windows/**
        - test/**
        - .metadata
        - analysis_options.yaml
        - Dockerfile
        - nginx.conf
        - render.yaml
